// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXIf_tZFr_SS2JAm8lmsJWbxuAJT6_PY',
    appId: '1:974788258846:web:cbc9d06322d2302bf6520f',
    messagingSenderId: '974788258846',
    projectId: 'armywiki-b1aa7',
    authDomain: 'armywiki-b1aa7.firebaseapp.com',
    storageBucket: 'armywiki-b1aa7.appspot.com',
    measurementId: 'G-C6HX2L5ZS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8V_mzwfSk2Rjp6xHdgjDqq5zGhww8hDA',
    appId: '1:974788258846:android:1356362217c3bfd9f6520f',
    messagingSenderId: '974788258846',
    projectId: 'armywiki-b1aa7',
    storageBucket: 'armywiki-b1aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwek5ALS-azsR0MpLRh403gNRqpZorH4',
    appId: '1:974788258846:ios:0ca313a973e9573bf6520f',
    messagingSenderId: '974788258846',
    projectId: 'armywiki-b1aa7',
    storageBucket: 'armywiki-b1aa7.appspot.com',
    iosBundleId: 'com.armywiki.app',
  );

}